# Generated by Django 6.0.1 on 2026-10-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_path",
            field=models.CharField(
                blank=True,
                help_text="Optional image path relative to static/, such as images/pic03.jpg.",
                max_length=200,
            ),
        ),
    ]
